import Mojito from "../../imgs/mojito.jpg";

const checkState = {
  types: {
    ISTJ: "Mojito",
    ISTP: "Mojito",
    ISFJ: "Mojito",
    ISFP: "Mojito",
    INTJ: "Mojito",
    INTP: "Mojito",
    INFJ: "Mojito",
    INFP: "Mojito",
    ESTJ: "Mojito",
    ESTP: "Mojito",
    ESFJ: "Mojito",
    ESFP: "Mojito",
    ENTJ: "Mojito",
    ENTP: "Mojito",
    ENFJ: "Mojito",
    ENFP: "Mojito",
  },

  typeImgs: {
    ISTJ: Mojito,
    ISTP: Mojito,
    ISFJ: Mojito,
    ISFP: Mojito,
    INTJ: Mojito,
    INTP: Mojito,
    INFJ: Mojito,
    INFP: Mojito,
    ESTJ: Mojito,
    ESTP: Mojito,
    ESFJ: Mojito,
    ESFP: Mojito,
    ENTJ: Mojito,
    ENTP: Mojito,
    ENFJ: Mojito,
    ENFP: Mojito,
  },
  typeInfos: {
    ISTJ: "MojitoMojito",
    ISTP: "MojitoMojito",
    ISFJ: "MojitoMojito",
    ISFP: "MojitoMojito",
    INTJ: "MojitoMojito",
    INTP: "MojitoMojito",
    INFJ: "MojitoMojito",
    INFP: "MojitoMojito",
    ESTJ: ["Mojito", <br />, "Mojito"],
    ESTP: "MojitoMojito",
    ESFJ: "MojitoMojito",
    ESFP: "MojitoMojito",
    ENTJ: "MojitoMojito",
    ENTP: "MojitoMojito",
    ENFJ: "MojitoMojito",
    ENFP: "MojitoMojito",
  },
};
export default checkState;
