import Mojito from "../../imgs/mojito.jpg";

const checkState = {
  types: {
    ISTJ: "Mojito",
    ISTP: "Mojito",
    ISFJ: "Mojito",
    ISFP: "Mojito",
    INTJ: "Mojito",
    INTP: "Mojito",
    INFJ: "Mojito",
    INFP: "Mojito",
    ESTJ: "Mojito",
    ESTP: "Mojito",
    ESFJ: "Mojito",
    ESFP: "Mojito",
    ENTJ: "Mojito",
    ENTP: "Mojito",
    ENFJ: "Mojito",
    ENFP: "Mojito",
  },

  typeImgs: {
    ISTJ: Mojito,
    ISTP: Mojito,
    ISFJ: Mojito,
    ISFP: Mojito,
    INTJ: Mojito,
    INTP: Mojito,
    INFJ: Mojito,
    INFP: Mojito,
    ESTJ: Mojito,
    ESTP: Mojito,
    ESFJ: Mojito,
    ESFP: Mojito,
    ENTJ: Mojito,
    ENTP: Mojito,
    ENFJ: Mojito,
    ENFP: Mojito,
  },
  typeInfos: {
    ISTJ: "MojitoMojitoISTJ",
    ISTP: "MojitoMojitoISTP",
    ISFJ: "MojitoMojitoISFJ",
    ISFP: "MojitoMojitoISFP",
    INTJ: "MojitoMojitoINTJ",
    INTP: "MojitoMojitoINTP",
    INFJ: "MojitoMojitoINFJ",
    INFP: "MojitoMojitoINFP",
    ESTJ: ["Mojito", <br />, "MojitoESTJ"],
    ESTP: "MojitoMojitoESTP",
    ESFJ: "MojitoMojitoESFJ",
    ESFP: "MojitoMojitoMojitoMojitoMojitoESFP",
    ENTJ: "MojitoMojitoENTJ",
    ENTP: "MojitoMojitoENTP",
    ENFJ: "MojitoMojitoENFJ",
    ENFP: "MojitoMojitoENFP",
  },
};
export default checkState;
